name: flutter_link_previewer
description: >
  URL preview extracted from the provided text with
  basic customization and ability to render from cached data.
version: 2.6.4
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.0.0"
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types:
    git:
      url: https://github.com/amsyary/flutter_chat_types.git
      ref: 8512211967d82a6ea6218740a5839e239fd1970a
  flutter_linkify: ^5.0.2
  html: ^0.15.0
  http: ^0.13.4
  linkify: ^4.1.0
  meta: ^1.7.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
